services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: okaberoot
      MARIADB_DATABASE: RANKING
      MARIADB_USER: okabe
      MARIADB_PASSWORD: okabe
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  app:
    container_name: golang
    build:
      context: .
      dockerfile: ./go/Dockerfile
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    