services:
  db:
    container_name: db
    image: yoshida1120/server-db:latest
    build:
      context: ./db
      #dockerfile: ./db/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: okaberoot
      MARIADB_ROOT_HOST: '%'
      MARIADB_DATABASE: RANKING
      MARIADB_USER: okabe
      MARIADB_PASSWORD: okabe
      TZ: 'Asia/Tokyo'
    privileged: true
    networks:
      - okb_network
    volumes:
      - ./db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3305:3305'
  app:
    container_name: golang
    image: yoshida1120/server-app:latest
    build:
      context: ./go
      #dockerfile: ./go/Dockerfile
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    privileged: true
    networks:
      - okb_network
    depends_on:
      - db
    command:
      - /bin/bash
volumes:
  gcloud_config_data:
networks:
  okb_network:
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16